src/main/java/com/exasol/adapter/json/RequestJsonParser.java
src/main/java/com/exasol/adapter/metadata/DataType.java
src/main/java/com/exasol/adapter/sql/SqlFunctionAggregate.java
src/main/java/com/exasol/adapter/sql/SqlFunctionScalar.java
src/main/java/com/exasol/adapter/sql/SqlGroupBy.java
src/main/java/com/exasol/adapter/sql/SqlOrderBy.java
src/main/java/com/exasol/adapter/sql/SqlPredicateAnd.java
src/main/java/com/exasol/adapter/sql/SqlPredicateInConstList.java
src/main/java/com/exasol/adapter/sql/SqlSelectList.java
src/main/java/com/exasol/adapter/sql/SqlSelectListType.java
src/test/java/com/exasol/adapter/json/RequestJsonParserTest.java
src/test/java/com/exasol/adapter/sql/SqlNodeTest.java

This is a second branch with fixes of sonar findings. The first one is already merged and the third is coming.

#15: fixed a part of sonar findings

---

pom.xml
src/main/java/com/exasol/adapter/json/RequestJsonParser.java
src/main/java/com/exasol/adapter/sql/SqlColumn.java

These preparations are necessary to continue with the development of the join pushdown in the adapter. 
These changes are only internal, no changed behavior or additional features.

Preparations for join pushdown 

---

launch/virtual-schema-common all tests.launch
pom.xml
src/main/java/com/exasol/logging/CompactFormatter.java
src/test/java/com/exasol/logging/CompactFormatterTest.java

#47: Moved `CompactFormatter` and added unit tests.

---

pom.xml
src/main/java/com/exasol/adapter/capabilities/MainCapability.java

Added JOIN Capabilities (see #60).
Please propose a proper Version.

JOIN capabilities

---

pom.xml
src/main/java/com/exasol/adapter/request/parser/RequestParser.java
src/main/java/com/exasol/adapter/request/parser/RequestParserConstants.java
src/test/java/com/exasol/adapter/request/parser/RequestParserTest.java

#70: Added missing parsing for tables to be refreshed.

---

pom.xml
src/main/java/com/exasol/adapter/AdapterFactory.java
src/main/java/com/exasol/adapter/AdapterRegistry.java
src/test/java/com/exasol/adapter/DummyAdapterFactory.java
src/test/java/com/exasol/adapter/RequestDispatcherTest.java

#83: added method that get the adapter version into AdapterFactory

---

pom.xml
src/main/java/com/exasol/adapter/metadata/DataType.java
src/test/java/com/exasol/adapter/metadata/DataTypeTest.java

#93: added createUnsupported() method to the DataType class

---

pom.xml
src/main/java/com/exasol/adapter/AdapterProperties.java
src/main/java/com/exasol/adapter/BinaryColumnHandling.java
src/test/java/com/exasol/adapter/AdapterPropertiesTest.java

Closes #239.
Task-Url: https://github.com/exasol/virtual-schemas/issues/239

#239: General binary column handling

---

pom.xml
src/main/java/com/exasol/adapter/metadata/DataType.java
src/test/java/com/exasol/adapter/metadata/DataTypeTest.java

Closes #103.
Task-Url: http://github.com/exasol/virtual-schema-common-java/issues/103

#103: Add `DataType.isSupported`

---

launch/virtual-schema-common clean.launch
launch/virtual-schema-common install.launch
launch/virtual-schema-common package.launch
pom.xml

Closes #107.
Task-Url: http://github.com/exasol/virtual-schema-common-java/issues/107

#107: Update Eclipse launch files to Java 9

---

pom.xml
src/main/java/com/exasol/adapter/RequestDispatcher.java
src/main/java/com/exasol/adapter/sql/SqlSelectList.java
src/main/java/com/exasol/logging/CompactFormatter.java
src/test/java/com/exasol/adapter/RequestDispatcherTest.java
src/test/java/com/exasol/logging/CompactFormatterTest.java

Closes #109.
Task-Url: http://github.com/exasol/virtual-schema-common-java/issues/109

#109: Log exceptions

---

pom.xml
src/main/java/com/exasol/adapter/AdapterFactory.java
src/main/java/com/exasol/adapter/AdapterRegistry.java
src/main/java/com/exasol/adapter/RequestDispatcher.java
src/test/java/com/exasol/adapter/AdapterRegistryTest.java
src/test/java/com/exasol/adapter/DummyAdapterFactory.java

#116: Initializing adapter registry on first use.

---

pom.xml
src/test/java/com/exasol/adapter/AbstractAdapterPropertiesTest.java
src/test/java/com/exasol/adapter/AdapterPropertiesTest.java
src/test/java/com/exasol/adapter/AdapterRegistryTest.java
src/test/java/com/exasol/adapter/RequestDispatcherTest.java
src/test/java/com/exasol/adapter/capabilities/CapabilityAssertions.java
src/test/java/com/exasol/adapter/metadata/TableMetadataTest.java
src/test/java/com/exasol/adapter/request/LoggingConfigurationTest.java
src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
src/test/java/com/exasol/adapter/request/parser/RequestParserTest.java
src/test/java/com/exasol/adapter/request/parser/SchemaMetadataParserTest.java
src/test/java/com/exasol/logging/CompactFormatterTest.java
src/test/java/com/exasol/logging/RemoteLogManagerTest.java
src/test/java/com/exasol/utils/JsonHelperTest.java

#129: updated dependencies

---

doc/changes/changes_12.1.0.md
src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
src/main/java/com/exasol/adapter/sql/SqlFunctionAggregateListagg.java
src/test/java/com/exasol/adapter/sql/SqlFunctionAggregateListaggTest.java

#173: Improved LISTAGG function class.

---

doc/changes/changes_12.1.0.md
src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
src/main/java/com/exasol/adapter/sql/SqlFunctionScalarExtract.java
src/test/java/com/exasol/adapter/sql/SqlFunctionScalarExtractTest.java

* #175: Improved EXTRACT function class.

---

doc/changes/changes_12.1.0.md
doc/development/api/virtual_schema_api.md

* #177: Improved the API documentation for LIKE and REGEXP_LIKE.

---

.github/workflows/maven_central_release.yml
doc/changes/changes_12.1.0.md
pom.xml

* #178: Prepared the project for an automated Maven Central Release

---

doc/changes/changes_next.md
src/main/java/com/exasol/adapter/capabilities/MainCapability.java

#190: Improved SELECTLIST_EXPRESSIONS documentation

---

doc/development/api/virtual_schema_api.md

#186: Improved the API documentation: selectList

---

src/main/java/com/exasol/adapter/capabilities/MainCapability.java

#190: Fixed SELECTLIST_EXPRESSIONS documentation

---

.settings/org.eclipse.m2e.core.prefs
doc/changes/changes_14.0.1.md
src/main/java/com/exasol/adapter/request/parser/RequestParser.java
src/main/java/com/exasol/adapter/request/parser/TablesMetadataParser.java
src/test/java/com/exasol/adapter/request/parser/TablesMetadataParserTest.java

Unify `parseInvolvedTables` method in the `RequestParser`

---

doc/changes/changes_15.0.0.md
doc/development/api/virtual_schema_api.md

* #186: Updated select list API description.

---

doc/changes/changelog.md
doc/changes/changes_15.0.1.md
launch/virtual-schema-common all tests.launch
pom.xml
src/main/java/com/exasol/adapter/AdapterProperties.java
src/test/java/com/exasol/adapter/AdapterPropertiesTest.java
src/test/java/com/exasol/adapter/RequestDispatcherTest.java
src/test/java/com/exasol/adapter/request/parser/RequestParserTest.java

Removed `SQL_DIALECT_PROPERTY` from `AdapterProperties`

---

doc/changes/changes_15.1.0.md
pom.xml

Release 15.1.0

---

doc/development/api/virtual_schema_api.md

#233: Link to Callback Function Documentation

---

doc/changes/changelog.md
doc/changes/changes_15.2.1.md
pom.xml
src/main/java/com/exasol/adapter/request/RequestJsonKeys.java
src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
src/main/java/com/exasol/adapter/request/renderer/PushdownSqlRenderer.java
src/main/java/com/exasol/adapter/sql/SqlGroupBy.java
src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
src/test/java/com/exasol/adapter/request/renderer/PushdownSqlRendererTest.java

* #229: Added missing parsing for the `aggregationType` field of the request

---

.github/workflows/release_droid_upload_github_release_assets.yml
dependencies.md
doc/changes/changes_15.2.1.md
pom.xml
src/main/java/com/exasol/adapter/metadata/converter/SchemaMetadataJsonConverter.java
src/main/java/com/exasol/adapter/request/parser/AbstractRequestParser.java
src/main/java/com/exasol/adapter/request/parser/PushdownSqlParser.java
src/main/java/com/exasol/adapter/request/parser/RequestParser.java
src/main/java/com/exasol/adapter/request/parser/SchemaMetadataInfoParser.java
src/main/java/com/exasol/adapter/request/parser/TablesMetadataParser.java
src/main/java/com/exasol/adapter/request/renderer/PushdownSqlRenderer.java
src/main/java/com/exasol/adapter/response/converter/ResponseJsonConverter.java
src/test/java/com/exasol/adapter/metadata/converter/SchemaMetadataJsonConverterTest.java
src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java
src/test/java/com/exasol/adapter/request/parser/SchemaMetadataParserTest.java
src/test/java/com/exasol/adapter/request/parser/TablesMetadataParserTest.java
src/test/java/com/exasol/adapter/request/renderer/PushdownSqlRendererTest.java

refactor/237: Replaced `javax.json` by `jakarta.json`

---

doc/changes/changelog.md
doc/changes/changes_15.3.1.md
pom.xml
src/main/java/com/exasol/adapter/RequestDispatcher.java

bug/227: Fixed incomplete logs

---

dependencies.md
doc/changes/changelog.md
doc/changes/changes_15.3.3.md
doc/development/api/virtual_schema_api.md
pk_generated_parent.pom
pom.xml

#247: Fixed "set properties" request in API documentation

---

.github/workflows/release_droid_upload_github_release_assets.yml
.project-keeper.yml

See also https://github.com/exasol/project-keeper/issues/371

fixed script release_droid_upload_github_release_assets.yml

---

doc/changes/changelog.md
doc/changes/changes_16.1.0.md
error_code_config.yml
pk_generated_parent.pom
pom.xml
src/main/java/com/exasol/adapter/metadata/converter/SchemaMetadataJsonConverter.java
src/main/java/com/exasol/adapter/request/parser/DataTypeParser.java
src/main/java/com/exasol/adapter/request/parser/DataTypeProperty.java
src/test/java/com/exasol/adapter/request/parser/DataTypeParserTest.java

#253: Fixed data type properties

---

doc/changes/changelog.md
doc/changes/changes_16.1.1.md
doc/development/api/capabilities_list.md
doc/development/api/data_types_api.md
doc/development/api/scalar_functions_api.md
doc/development/api/virtual_schema_api.md
doc/error_codes.md
pk_generated_parent.pom
pom.xml

#255: Improved documentation

---

dependencies.md
doc/changes/changelog.md
doc/changes/changes_16.1.3.md
doc/development/api/capabilities_list.md
pk_generated_parent.pom
pom.xml
src/main/java/com/exasol/adapter/capabilities/AggregateFunctionCapability.java

#262: Deprecated outdated capabilities. Improved documentation.

---

doc/changes/changelog.md
doc/changes/changes_16.1.4.md
doc/development/api/virtual_schema_api.md
pk_generated_parent.pom
pom.xml

#264: Documentation update

---

README.md
doc/changes/changelog.md
doc/changes/changes_16.1.5.md
pk_generated_parent.pom
pom.xml

#266: Documentation update

---

.vscode/settings.json
dependencies.md
doc/changes/changelog.md
doc/changes/changes_16.2.0.md
pk_generated_parent.pom
pom.xml

#270: Updated dependencies

---

doc/changes/changes_18.0.0.md
doc/design.md
doc/development/developer_guide.md
doc/system_requirements.md
error_code_config.yml
src/main/java/com/exasol/adapter/properties/EnumerationValidator.java
src/main/java/com/exasol/adapter/properties/MultiSelectValidator.java
src/main/java/com/exasol/adapter/properties/UnixPathValidator.java
src/main/java/com/exasol/adapter/properties/ValidationResult.java
src/main/java/com/exasol/adapter/properties/ValidatorFactory.java
src/test/java/com/exasol/adapter/properties/EnumerationValidatorTest.java
src/test/java/com/exasol/adapter/properties/MultiSelectValidatorTest.java
src/test/java/com/exasol/adapter/properties/UnixPathValidatorTest.java

#287: Multi-Select and Unix Path Validator
